name: CI

on:
    - workflow_dispatch: {}

env:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "11076708"

jobs:
  lintDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        run: |
          export ANDROID_HOME="${PWD}/android-sdk-root"
          mkdir -p $ANDROID_HOME
          wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
          unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
          mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
          sdkmanager "platform-tools"
          sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
          chmod +x ./gradlew
      - name: Lint Debug
        run: ./gradlew -Pci --console=plain :app:lintBaseDebug -PbuildDir=lint
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/lint/reports/lint-results-debug.html

  assembleDebug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        run: |
          export ANDROID_HOME="${PWD}/android-sdk-root"
          mkdir -p $ANDROID_HOME
          wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
          unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
          mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
          sdkmanager "platform-tools"
          sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
          chmod +x ./gradlew
      - name: Assemble Debug
        run: ./gradlew assembleBaseDebug
      - uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: app/build/outputs/

  debugTests:
    runs-on: ubuntu-latest
    needs: [lintDebug, assembleDebug]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        run: |
          export ANDROID_HOME="${PWD}/android-sdk-root"
          mkdir -p $ANDROID_HOME
          wget --no-verbose --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
          unzip -q -d "$ANDROID_HOME/cmdline-tools" "$ANDROID_HOME/cmdline-tools.zip"
          mv -T "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/tools"
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
          sdkmanager "platform-tools"
          sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
          chmod +x ./gradlew
      - name: Run Tests
        run: ./gradlew -Pci --console=plain :app:testBaseDebug
